/* ══════════════════════════════════════════════════════════════
   AI for EveryOne Workshop — Frontend Logic
   ──────────────────────────────────────────────────────────────
   Secrets are NOT stored here. They are injected at deploy time
   via config.js, which is generated by GitHub Actions from
   repository secrets (Settings → Secrets and variables → Actions).

   Local dev: copy config.example.js → config.js, fill in values.
   config.js is gitignored — it never gets committed.
══════════════════════════════════════════════════════════════ */


/* ══════════════════════════════════════════════════════════════
   CONFIG  (read from window.APP_CONFIG set by config.js)
══════════════════════════════════════════════════════════════ */
var APP_CONFIG       = window.APP_CONFIG || {};
var GOOGLE_SHEET_URL = APP_CONFIG.GOOGLE_SHEET_URL || '';
var RAZORPAY_KEY_ID  = APP_CONFIG.RAZORPAY_KEY_ID  || '';
var GITHUB_TOKEN     = APP_CONFIG.GITHUB_TOKEN     || '';
var GITHUB_REPO      = APP_CONFIG.GITHUB_REPO      || 'karnkeshav/lets_do_AI';


/* ══════════════════════════════════════════════════════════════
   PLANS DATA
══════════════════════════════════════════════════════════════ */
var PLANS = [
    {
        id: 'track-a',
        track: 'TRACK A',
        name: 'AI Productivity Essentials',
        subtitle: 'Use AI Effectively',
        duration: '5 Days',
        originalPrice: 1999,
        price: 999,
        discount: '50% OFF',
        color: '#8B5CF6',
        isCombo: false,
        features: [
            'Understanding AI in Simple Language',
            'Prompt & Content Engineering AI Productivity',
            'Workflows for Daily Life & Work',
            'Which AI Tool to Use & When (ChatGPT, Gemini, Claude, Grok, etc.)',
            'Free vs Paid AI Tools — What Actually Matters',
            'AI Hygiene, Privacy & Guardrails',
            'NotebookLM & AI Knowledge Tools',
            'Open Source AI vs Closed AI — Simple Understanding',
            'AI Agents vs Agentic AI — What\'s the Difference?',
            'Real-Life Use Cases Across Students, Teachers, Businesses & Working Professionals',
        ],
    },
    {
        id: 'track-b',
        track: 'TRACK B',
        name: 'AI App Builder',
        subtitle: 'Build with AI',
        duration: '10 Days',
        originalPrice: 4999,
        price: 2499,
        discount: '50% OFF',
        color: '#10B981',
        isCombo: false,
        features: [
            'Introduction to Vibe Coding',
            'Building Apps Without Traditional Coding',
            'GitHub, Vercel, Supabase & Firebase',
            'Frontend + Backend Development Using AI',
            'Full Stack Development Without Prior Coding Experience',
            'GitHub Actions & Workflow Automation',
            'AI-Powered Web & Mobile App Development',
            'Serverless Deployment Made Simple',
            'Real Project Building from Idea to Deployment',
            'Connecting AI Models, APIs & Databases',
            'Launching SaaS Products & AI Tools Quickly',
        ],
    },
    {
        id: 'track-c',
        track: 'TRACK C',
        name: 'Advanced AI Workflows',
        subtitle: 'Control and Scale AI',
        duration: '5 Days',
        originalPrice: 2999,
        price: 1499,
        discount: '50% OFF',
        color: '#F59E0B',
        isCombo: false,
        features: [
            'API Integrations, API Keys & Unlimited AI Workflows',
            'Advanced Automation Systems Using AI',
            'Coding AI Agents (Copilot, Devin AI, Claude, etc.)',
            'Privacy-First & Secure AI Workflows',
            'Creating Personal GPTs & Private AI Assistants',
            'Creating AI Bots & Automation Workflows',
            'Working with APIs & AI Integrations',
            'Running AI Without Making Data Public',
            'Cloud AI Models on Azure, AWS & Google Cloud',
            'Open-Source AI Models (Ollama, Mistral, DeepSeek, etc.)',
            'Local AI Setup & Self-Hosted AI Systems',
        ],
    },
    {
        id: 'combo',
        track: 'ALL 3 TRACKS',
        name: 'Combo – Get All 3 Tracks',
        subtitle: 'Unlock everything. Learn everything. Build anything.',
        duration: '24+ Days',
        originalPrice: 9999,
        price: 4499,
        discount: '55% OFF',
        color: '#6366F1',
        isCombo: true,
        features: [
            'All 3 Tracks — Complete Access',
            '24+ Days of Total Learning',
            'Real Projects — Hands-on Learning',
            'Lifetime Access — Learn at Your Pace',
        ],
    },
];


/* ══════════════════════════════════════════════════════════════
   BATCHES DATA
══════════════════════════════════════════════════════════════ */
var BATCHES = [
    {
        id: 'weekday',
        name: 'Weekday Batch',
        days: 'Monday – Friday',
        time: '8:00 PM – 10:00 PM IST',
        icon: '💼',
        desc: 'Ideal for working professionals & students with weekends free',
    },
    {
        id: 'weekend',
        name: 'Weekend Batch',
        days: 'Saturday & Sunday',
        time: '10:00 AM – 1:00 PM IST',
        icon: '🌅',
        desc: 'Ideal for those who prefer a relaxed, deep-dive weekend pace',
    },
];


/* ══════════════════════════════════════════════════════════════
   STATE
══════════════════════════════════════════════════════════════ */
var state = {
    selectedPlan:  null,
    selectedBatch: null,
    registration:  {},
    paymentId:     null,
};


/* ══════════════════════════════════════════════════════════════
   STEP NAVIGATION
══════════════════════════════════════════════════════════════ */
function goToStep(n) {
    document.querySelectorAll('.step').forEach(function(el) {
        el.classList.remove('active');
    });
    document.getElementById('step-' + n).classList.add('active');
    window.scrollTo({ top: 0, behavior: 'instant' });
}


/* ══════════════════════════════════════════════════════════════
   PLAN CARDS
══════════════════════════════════════════════════════════════ */
function renderPlans() {
    var container = document.getElementById('plans-list');
    container.innerHTML = PLANS.map(function(plan) {
        var isSelected = state.selectedPlan && state.selectedPlan.id === plan.id;
        return '<div class="plan-card ' + (isSelected ? 'selected' : '') + '" ' +
               'style="--plan-color:' + plan.color + '" ' +
               'onclick="selectPlan(\'' + plan.id + '\')">' +

               '<div class="plan-check">✓</div>' +

               (plan.isCombo ? '<div class="combo-tag">★ Best Value</div>' : '') +

               '<div class="plan-top">' +
                   '<div style="min-width:0">' +
                       '<div class="plan-track">' + plan.track + '</div>' +
                       '<div class="plan-name">' + plan.name + '</div>' +
                       '<div class="plan-sub">' + plan.subtitle + '</div>' +
                   '</div>' +
                   '<div class="plan-duration">' + plan.duration + '</div>' +
               '</div>' +

               '<div class="plan-pricing">' +
                   '<span class="plan-original">₹' + plan.originalPrice.toLocaleString('en-IN') + '</span>' +
                   '<span class="plan-price">₹' + plan.price.toLocaleString('en-IN') + '</span>' +
                   '<span class="plan-badge">' + plan.discount + '</span>' +
               '</div>' +

               '<hr class="plan-divider">' +
               '<ul class="plan-features">' +
                   plan.features.map(function(f) { return '<li>' + f + '</li>'; }).join('') +
               '</ul>' +

               '</div>';
    }).join('');
}

function selectPlan(id) {
    state.selectedPlan = PLANS.find(function(p) { return p.id === id; });
    document.getElementById('plan-error').style.display = 'none';
    renderPlans();
}

function proceedFromPlanSelect() {
    if (!state.selectedPlan) {
        document.getElementById('plan-error').style.display = 'block';
        return;
    }
    state.selectedBatch = null;
    renderBatches();
    var plan = state.selectedPlan;
    document.getElementById('batch-plan-pill').innerHTML =
        '<div class="mini-plan-dot" style="background:' + plan.color + '"></div>' +
        '<span class="mini-plan-name">' + plan.name + '</span>' +
        '<span class="mini-plan-price">₹' + plan.price.toLocaleString('en-IN') + '</span>';
    goToStep(3);
}


/* ══════════════════════════════════════════════════════════════
   BATCH CARDS
══════════════════════════════════════════════════════════════ */
function renderBatches() {
    var container = document.getElementById('batch-list');
    container.innerHTML = BATCHES.map(function(batch) {
        var isSelected = state.selectedBatch && state.selectedBatch.id === batch.id;
        return '<div class="batch-card ' + (isSelected ? 'selected' : '') + '" ' +
               'onclick="selectBatch(\'' + batch.id + '\')">' +
                   '<div class="batch-icon">' + batch.icon + '</div>' +
                   '<div class="batch-info">' +
                       '<div class="batch-name">' + batch.name + '</div>' +
                       '<div class="batch-days">' + batch.days + '</div>' +
                       '<div class="batch-time">' + batch.time + '</div>' +
                       '<div class="batch-desc">' + batch.desc + '</div>' +
                   '</div>' +
                   '<div class="batch-check">✓</div>' +
               '</div>';
    }).join('');
}

function selectBatch(id) {
    state.selectedBatch = BATCHES.find(function(b) { return b.id === id; });
    document.getElementById('batch-error').style.display = 'none';
    renderBatches();
}

function proceedFromBatchSelect() {
    if (!state.selectedBatch) {
        document.getElementById('batch-error').style.display = 'block';
        return;
    }
    renderSelectedPlanPill();
    goToStep(4);
}


/* ══════════════════════════════════════════════════════════════
   REGISTRATION
══════════════════════════════════════════════════════════════ */
function renderSelectedPlanPill() {
    var plan  = state.selectedPlan;
    var batch = state.selectedBatch;
    document.getElementById('selected-plan-summary').innerHTML =
        '<div class="selected-plan-dot" style="background:' + plan.color + '"></div>' +
        '<div class="selected-plan-info">' +
            '<div class="selected-plan-name">' + plan.name + '</div>' +
            '<div class="selected-plan-price">₹' + plan.price.toLocaleString('en-IN') +
                '  ·  ' + plan.duration +
                (batch ? '  ·  ' + batch.name : '') +
            '</div>' +
        '</div>' +
        '<span class="change-link" onclick="goToStep(2)">Change</span>';
}

function handleRegister(e) {
    e.preventDefault();
    var name  = document.getElementById('field-name').value.trim();
    var email = document.getElementById('field-email').value.trim();
    var phone = document.getElementById('field-phone').value.trim();
    var errEl = document.getElementById('register-error');

    if (!name || !email || !phone) {
        errEl.style.display = 'block';
        return;
    }

    errEl.style.display = 'none';
    state.registration = { name: name, email: email, phone: phone };
    renderPaymentPage();
    goToStep(5);
}


/* ══════════════════════════════════════════════════════════════
   PAYMENT
══════════════════════════════════════════════════════════════ */
function renderPaymentPage() {
    var plan = state.selectedPlan;
    document.getElementById('pay-amount').textContent    = '₹' + plan.price.toLocaleString('en-IN');
    document.getElementById('pay-plan-name').textContent = plan.track + ' – ' + plan.name;
    var btn = document.getElementById('pay-btn');
    btn.classList.remove('loading');
    btn.innerHTML = 'Pay Securely  →';
    document.getElementById('payment-error').style.display = 'none';
}

function openRazorpayCheckout() {
    var plan  = state.selectedPlan;
    var batch = state.selectedBatch;
    var r     = state.registration;
    var btn   = document.getElementById('pay-btn');
    var errEl = document.getElementById('payment-error');

    errEl.style.display = 'none';

    if (typeof Razorpay === 'undefined') {
        errEl.innerHTML = 'Payment gateway failed to load. Check your internet connection and refresh.';
        errEl.style.display = 'block';
        return;
    }

    if (!RAZORPAY_KEY_ID) {
        errEl.innerHTML = 'Razorpay not configured. Add RAZORPAY_KEY_ID to GitHub repository secrets.';
        errEl.style.display = 'block';
        return;
    }

    btn.classList.add('loading');
    btn.innerHTML = '<div class="spinner"></div>&nbsp; Opening payment…';

    var options = {
        key:         RAZORPAY_KEY_ID,
        amount:      plan.price * 100,
        currency:    'INR',
        name:        'AI for EveryOne Workshop',
        description: plan.track + ' – ' + plan.name + (batch ? ' · ' + batch.name : ''),
        prefill: {
            name:    r.name,
            email:   r.email,
            contact: r.phone,
        },
        notes: {
            plan:  plan.track + ' – ' + plan.name,
            batch: batch ? batch.name : '',
        },
        theme: { color: plan.color },

        /* Fires automatically the INSTANT payment succeeds in the customer's UPI app */
        handler: function(response) {
            state.paymentId = response.razorpay_payment_id;

            var payload = {
                name:       r.name,
                email:      r.email,
                phone:      r.phone,
                plan:       plan.track + ' – ' + plan.name,
                batch:      batch ? batch.name + ' (' + batch.days + ')' : '',
                amount:     plan.price,
                payment_id: response.razorpay_payment_id,
                timestamp:  new Date().toISOString(),
            };

            saveToSheets(payload).catch(function(err) { console.error('Sheets:', err); });
            saveToGitHub(payload).catch(function(err)  { console.error('GitHub:', err); });

            renderThankYouPage();
            goToStep(6);
        },

        modal: {
            ondismiss: function() {
                btn.classList.remove('loading');
                btn.innerHTML = 'Pay Securely  →';
            }
        }
    };

    var rzp = new Razorpay(options);
    rzp.on('payment.failed', function(response) {
        btn.classList.remove('loading');
        btn.innerHTML = 'Pay Securely  →';
        errEl.innerHTML = 'Payment failed — ' + (response.error.description || 'please try again.');
        errEl.style.display = 'block';
    });

    rzp.open();
}


/* ══════════════════════════════════════════════════════════════
   GOOGLE SHEETS SAVE
   Uses GET + query params so data survives the 302 redirect that
   Apps Script issues. POST bodies are silently dropped on that
   redirect; GET params are part of the URL and survive intact.
══════════════════════════════════════════════════════════════ */
function saveToSheets(data) {
    if (!GOOGLE_SHEET_URL) {
        console.warn('GOOGLE_SHEET_URL not set — skipping Sheets save.');
        return Promise.resolve();
    }
    return fetch(GOOGLE_SHEET_URL + '?' + new URLSearchParams(data), { mode: 'no-cors' });
}


/* ══════════════════════════════════════════════════════════════
   GITHUB CSV SAVE
   Creates / appends registrations/YYYY-MM-DD.csv (IST date) in
   the GitHub repo. One file per calendar day, one row per
   registration. Requires a fine-grained PAT (Contents R+W) stored
   as the CSV_GITHUB_TOKEN repository secret.
══════════════════════════════════════════════════════════════ */
async function saveToGitHub(data) {
    if (!GITHUB_TOKEN) {
        console.warn('GITHUB_TOKEN not set — skipping CSV save.');
        return;
    }

    var today = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Kolkata' }); // YYYY-MM-DD
    var path  = 'registrations/' + today + '.csv';
    var url   = 'https://api.github.com/repos/' + GITHUB_REPO + '/contents/' + path;
    var hdrs  = {
        'Authorization':        'Bearer ' + GITHUB_TOKEN,
        'Accept':               'application/vnd.github+json',
        'Content-Type':         'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
    };

    /* Step 1 — fetch existing file (sha + content) so we can append */
    var sha = '', existingCsv = '';
    try {
        var getRes = await fetch(url, { headers: hdrs });
        if (getRes.ok) {
            var fileData = await getRes.json();
            sha = fileData.sha;
            existingCsv = decodeURIComponent(escape(atob(fileData.content.replace(/\n/g, ''))));
        }
    } catch (e) { /* file doesn't exist yet — first registration of the day */ }

    /* Step 2 — build CSV row */
    function csvCell(v) { return '"' + String(v || '').replace(/"/g, '""') + '"'; }
    var newRow = [
        new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
        data.name, data.email, data.phone,
        data.plan, data.batch, data.amount, data.payment_id,
    ].map(csvCell).join(',');

    var HEADER = '"Timestamp (IST)","Name","Email","Phone","Plan","Batch","Amount (INR)","Razorpay Payment ID"';
    var csv    = (existingCsv || HEADER + '\n') + newRow + '\n';

    /* Step 3 — PUT (create or update) */
    var putBody = {
        message: 'reg: ' + (data.name || 'unknown') + ' | ' + today,
        content: btoa(unescape(encodeURIComponent(csv))), // Unicode-safe base64
    };
    if (sha) putBody.sha = sha;

    try {
        var putRes = await fetch(url, { method: 'PUT', headers: hdrs, body: JSON.stringify(putBody) });
        if (!putRes.ok) {
            console.error('GitHub PUT failed (' + putRes.status + '):', await putRes.text());
        } else {
            console.log('Registration saved to GitHub:', path);
        }
    } catch (e) {
        console.error('GitHub save error:', e);
    }
}


/* ══════════════════════════════════════════════════════════════
   THANK YOU
══════════════════════════════════════════════════════════════ */
function renderThankYouPage() {
    var r     = state.registration;
    var plan  = state.selectedPlan;
    var batch = state.selectedBatch;

    document.getElementById('thankyou-message').innerHTML =
        'Thank you for your payment, <strong>' + r.name + '</strong>! 🎉<br><br>' +
        'Welcome to <span style="color:' + plan.color + ';font-weight:700">' + plan.name + '</span>' +
        (batch ? ' — <strong>' + batch.name + '</strong>' : '') + '.<br><br>' +
        'We will inform you of the upcoming batch schedule and joining details on your WhatsApp number <strong>' + r.phone + '</strong>.';

    document.getElementById('thank-you-summary').innerHTML =
        summaryRow('Name',        r.name) +
        summaryRow('Email',       r.email) +
        summaryRow('WhatsApp',    r.phone) +
        summaryRow('Plan',        '<span style="color:' + plan.color + ';font-weight:700">' + plan.name + '</span>') +
        summaryRow('Batch',       batch ? batch.name + '<br><span style="font-size:12px;color:var(--muted)">' + batch.days + ' · ' + batch.time + '</span>' : '–') +
        summaryRow('Duration',    plan.duration) +
        summaryRow('Amount Paid', '&#8377;' + plan.price.toLocaleString('en-IN')) +
        (state.paymentId ? summaryRow('Payment ID', '<span style="font-size:12px;word-break:break-all">' + state.paymentId + '</span>') : '') +
        summaryRow('Status',      '<span class="status-pill">Confirmed ✓</span>');
}

function summaryRow(key, val) {
    return '<div class="summary-row">' +
           '<span class="summary-key">' + key + '</span>' +
           '<span class="summary-val">'  + val + '</span>' +
           '</div>';
}


/* ══════════════════════════════════════════════════════════════
   INIT
══════════════════════════════════════════════════════════════ */
renderPlans();
renderBatches();
